language: java
jdk: oraclejdk8
addons:
  apt:
    packages:
      - oracle-java8-installer  # https://github.com/travis-ci/travis-ci/issues/3259

# This skips the mvn install that is otherwise run (implausibly, the setting has to be "true")
# https://docs.travis-ci.com/user/customizing-the-build/#Skipping-the-Installation-Step
install: true

# define the order of the stages:
stages:
  - package
  - test
  - deploy

script:
  - mvn install --also-make --projects ${MODULE} -DskipTests && cd ${TRAVIS_BUILD_DIR}/${MODULE} && mvn failsafe:integration-test failsafe:verify -B -Dmaven.test.redirectTestOutputToFile -Dmatsim.preferLocalDtds=true --fail-at-end

jobs:
  include:
    - stage: package
      script: mvn package -B -Dmaven.test.redirectTestOutputToFile -Dmatsim.preferLocalDtds=true --fail-at-end
    - stage: deploy
      script: "mvn --settings .travis.settings.xml -DskipTests=true -B clean deploy"
      skip_cleanup: true

env:
  global:
    - MAVEN_OPTS="-Xmx2g"
  matrix:
    - MODULE=up            # 5 min 29 sec
    # sorted from longest to shortest (to minimise the overall test stage duration)
    - MODULE=jwjoubert      # 28 min 51 sec
    - MODULE=djdebeer       # 10 min 34 sec
    - MODULE=nmviljoen      # 8 min 39 sec
    - MODULE=onnene         # 8 min 9 sec
    
cache:
  directories:
  - $HOME/.m2
